//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "allowed_payloads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_type_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub payload_type_id: i64,
    #[sea_orm(
        belongs_to,
        from = "event_type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event_types: HasOne<super::event_types::Entity>,
    #[sea_orm(
        belongs_to,
        from = "payload_type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub payload_types: HasOne<super::payload_types::Entity>,
}
