//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "event_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code_name: String,
    pub description: Option<String>,
    #[sea_orm(has_many)]
    pub events: HasMany<super::events::Entity>,
    #[sea_orm(has_many, via = "allowed_payloads")]
    pub payload_types: HasMany<super::payload_types::Entity>,
}
