//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub client_id: i64,
    pub event_type_id: i64,
    pub triggered_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "client_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub client_ids: HasOne<super::client_ids::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event_types: HasOne<super::event_types::Entity>,
    #[sea_orm(has_many)]
    pub payloads: HasMany<super::payloads::Entity>,
}
