//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "goal_right_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub goal_right_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    #[sea_orm(
        belongs_to,
        from = "goal_right_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub goal_rights: HasOne<super::goal_rights::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub roles: HasOne<super::roles::Entity>,
}
