//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "goal_rights")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub goal_id: i64,
    pub right_id: i64,
    #[sea_orm(
        belongs_to,
        from = "goal_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub goals: HasOne<super::goals::Entity>,
    #[sea_orm(
        belongs_to,
        from = "right_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub rights: HasOne<super::rights::Entity>,
    #[sea_orm(has_many, via = "goal_right_roles")]
    pub roles: HasMany<super::roles::Entity>,
}
