//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod allowed_payloads;
pub mod client_ids;
pub mod event_types;
pub mod events;
pub mod goal_right_roles;
pub mod goal_rights;
pub mod goals;
pub mod payload_types;
pub mod payloads;
pub mod refresh_tokens;
pub mod rights;
pub mod roles;
pub mod user_roles;
pub mod users;
pub mod value_types;

seaography::register_entity_modules!([
    allowed_payloads,
    client_ids,
    event_types,
    events,
    goal_right_roles,
    goal_rights,
    goals,
    payload_types,
    payloads,
    refresh_tokens,
    rights,
    roles,
    user_roles,
    users,
    value_types,
]);
