//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "payload_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub code_name: String,
    pub description: Option<String>,
    pub value_type_id: i64,
    #[sea_orm(has_many)]
    pub payloads: HasMany<super::payloads::Entity>,
    #[sea_orm(
        belongs_to,
        from = "value_type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub value_types: HasOne<super::value_types::Entity>,
    #[sea_orm(has_many, via = "allowed_payloads")]
    pub event_types: HasMany<super::event_types::Entity>,
}
