//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "payloads")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub event_id: i64,
    pub type_id: i64,
    pub value: String,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub events: HasOne<super::events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "type_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub payload_types: HasOne<super::payload_types::Entity>,
}
